# CLI

brew 'atuin'
brew 'zsh'

# Kubernetes

brew 'k9s'
brew 'kustomize'
brew 'kubernetes-cli'

# Terraform
brew 'terraform'
brew 'terragrunt'
brew 'opentofu'
brew 'tflint'
brew 'tfsec'

# Ansible
brew 'ansible-lint'
brew 'ansible'

# ZSH
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'
brew 'zsh-history-substring-search'

# Other
brew 'go-task'

# Go
brew 'go'
