# CLI

brew 'atuin'
brew 'zsh'

# Kubernetes

brew 'k9s'
brew 'kustomize'

# Terraform
brew 'terragrunt'
brew 'opentofu'
brew 'tflint'
brew 'tfsec'

# Ansible
brew 'ansible-lint'
brew 'ansible'

# ZSH
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'

# Other
brew 'go-task'
